on:         
  workflow_dispatch:

name: php check
jobs:
  php-check:
    name:  Check
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: PHP Lint
      # You may pin to the exact commit or the version.
      # uses: michaelw90/PHP-Lint@0d9e19434b05c780f6cc87fa573bbc6061dbfe24
      uses: michaelw90/PHP-Lint@2.1.0
          
    
